# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb8dd32e0d8d3a65685fb25988235d2f88189fe7f534e8925cf533b640dea2b55956f30cf56498058d5e1c3672c28f2295056008165c3a3cb58dbbda6fa1118f

test:
  secret_key_base: e983fc85d97be07ee9d6d59e8bbb5dccd5b6de6361c7a6d7b2c12fe4a777636a02994f4876561e421bb87e92d2986c41cf46b1a46ec9a325f99d3de9aa7ac1c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
